from typing import Dict

from app.models.schema_common import (
    KST,
    get_kst_now,
    ErrorResponse,
    MissingStockData,
    BacktestDataError,
)

from app.models.schema_stock import (
    StockCreate,
    StockResponse,
    StockPriceCreate,
    StockPriceResponse,
    StockPriceCollectionRequest,
    StockPriceQueryRequest,
    AggregateResult,
    BenchmarkPriceResponse,
    RiskFreeRateResponse,
)

from app.models.schema_backtest import (
    Holding,
    TradingRule,
    TradingRules,
    BacktestRequest,
    BacktestMetrics,
    BenchmarkMetrics,
    HoldingSnapshotResponse,
    PortfolioSnapshotResponse,
    StockDailyData,
    ResultSummary,
    ExecutionLog,
    BacktestResponse,
    BacktestJobResponse,
    BacktestCallbackResponse,
)

from app.models.schema_analysis import (
    AnalysisHoldingInput,
    AnalysisRequest,
    BetaAnalysis,
    AnalysisMetrics,
    StockDetails,
    BenchmarkComparison,
    PortfolioData,
    AnalysisMetadata,
    BenchmarkInfo,
    PortfolioAnalysisResponse,
    AnalysisJobResponse,
    AnalysisCallbackMetadata,
    AnalysisCallbackResponse,
)

PortfolioWeights = Dict[str, float]

__all__ = [
    "KST",
    "get_kst_now",
    "ErrorResponse",
    "MissingStockData",
    "BacktestDataError",
    "StockCreate",
    "StockResponse",
    "StockPriceCreate",
    "StockPriceResponse",
    "StockPriceCollectionRequest",
    "StockPriceQueryRequest",
    "AggregateResult",
    "BenchmarkPriceResponse",
    "RiskFreeRateResponse",
    "Holding",
    "TradingRule",
    "TradingRules",
    "BacktestRequest",
    "BacktestMetrics",
    "BenchmarkMetrics",
    "HoldingSnapshotResponse",
    "PortfolioSnapshotResponse",
    "StockDailyData",
    "ResultSummary",
    "ExecutionLog",
    "BacktestResponse",
    "BacktestJobResponse",
    "BacktestCallbackResponse",
    "AnalysisHoldingInput",
    "AnalysisRequest",
    "BetaAnalysis",
    "AnalysisMetrics",
    "StockDetails",
    "BenchmarkComparison",
    "PortfolioData",
    "AnalysisMetadata",
    "BenchmarkInfo",
    "PortfolioAnalysisResponse",
    "AnalysisJobResponse",
    "AnalysisCallbackMetadata",
    "AnalysisCallbackResponse",
    "PortfolioWeights",
]
